docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Installation: installation.md
    - "Quick Start": quick-start.md
    - Reference:
        - Elements:
            - Introduction: element/intro.md
            - Element: element/element.md
            - button: element/button.md
            - CAPTCHA: element/captcha.md
            - checkbox: element/checkbox.md
            - Collection: element/collection.md
            - color: element/color.md
            - CSRF: element/csrf.md
            - date: element/date.md
            - datetime: element/date-time.md
            - datetime-local: element/date-time-local.md
            - email: element/email.md
            - file: element/file.md
            - hidden: element/hidden.md
            - image: element/image.md
            - month: element/month.md
            - MonthSelect: element/month-select.md
            - MultiCheckbox: element/multi-checkbox.md
            - number: element/number.md
            - password: element/password.md
            - radio: element/radio.md
            - range: element/range.md
            - search: element/search.md
            - select: element/select.md
            - submit: element/submit.md
            - tel: element/tel.md
            - text: element/text.md
            - textarea: element/textarea.md
            - time: element/time.md
            - url: element/url.md
            - week: element/week.md
        - Collections: collections.md
        - "File Uploads": file-upload.md
        - "View Helpers":
            - Introduction: helper/intro.md
            - AbstractHelper: helper/abstract-helper.md
            - formInput: helper/form-input.md
            - formElement: helper/form-element.md
            - formElementErrors: helper/form-element-errors.md
            - formLabel: helper/form-label.md
            - formRow: helper/form-row.md
            - formCollection: helper/form-collection.md
            - form: helper/form.md
            - formButton: helper/form-button.md
            - formCaptcha: helper/form-captcha.md
            - formCheckbox: helper/form-checkbox.md
            - formColor: helper/form-color.md
            - formDate: helper/form-date.md
            - formDateTime: helper/form-date-time.md
            - formDateTimeLocal: helper/form-date-time-local.md
            - formEmail: helper/form-email.md
            - formFile: helper/form-file.md
            - formHidden: helper/form-hidden.md
            - formImage: helper/form-image.md
            - formMonth: helper/form-month.md
            - formMonthSelect: helper/form-month-select.md
            - formMultiCheckbox: helper/form-multicheckbox.md
            - formNumber: helper/form-number.md
            - formPassword: helper/form-password.md
            - formRadio: helper/form-radio.md
            - formRange: helper/form-range.md
            - formReset: helper/form-reset.md
            - formSearch: helper/form-search.md
            - formSelect: helper/form-select.md
            - formSubmit: helper/form-submit.md
            - formTel: helper/form-tel.md
            - formText: helper/form-text.md
            - formTextarea: helper/form-textarea.md
            - formTime: helper/form-time.md
            - formUrl: helper/form-url.md
            - formWeek: helper/form-week.md
            - "Upload Progress":
                - Introduction: helper/upload-progress-helpers.md
                - formFileApcProgress: helper/form-file-apc-progress.md
                - formFileSessionProgress: helper/form-file-session-progress.md
                - formFileUploadProgress: helper/form-file-upload-progress.md
        - Advanced: advanced.md
    - "Application Integration":
        - "Usage in a laminas-mvc application": application-integration/usage-in-a-laminas-mvc-application.md
site_name: laminas-form
site_description: "Validate and display simple and complex forms, casting forms to business objects and vice versa."
repo_url: 'https://github.com/laminas/laminas-form'
extra:
    project: Components
    installation:
        config_provider_class: 'Laminas\Form\ConfigProvider'
        module_class: 'Laminas\Form\Module'
