name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
    tags:

env:
  default_php: 8.2
  php_extensions: intl

jobs:
  matrix:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      -   name: Gather CI configuration
          id: matrix
          uses: laminas/laminas-ci-matrix-action@fd1e60db9fc0f385775d91a73ea7410bcc7b2e70 # v1

  qa:
    name: QA Checks
    needs: [ matrix ]
    runs-on: ${{ matrix.operatingSystem }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      -   name: ${{ matrix.name }}
          uses: laminas/laminas-continuous-integration-action@757a62736b25b11240101d3c616fff4cbc707cfd # v1
          with:
            job: ${{ matrix.job }}

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shivammathur/setup-php@2.37.1

        with:
          php-version: ${{ env.default_php }}
          ini-values: memory_limit=-1
          extensions: ${{ env.php_extensions }}
      - uses: ramsey/composer-install@4.0.0
      - run: make install-tools
      - run: make composer-require-checker

  rector:
    name: Rector on Default PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shivammathur/setup-php@2.37.1
        with:
          php-version: ${{ env.default_php }}
          tools: composer
      - uses: ramsey/composer-install@4.0.0
      - run: make install-tools
      - run: make rector-ci
